// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotificationPro;

namespace NotificationPro.Migrations
{
    [DbContext(typeof(CommonContext))]
    partial class CommonContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NotificationPro.Entities.Link", b =>
                {
                    b.Property<string>("Links")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Act");

                    b.Property<string>("Status");

                    b.Property<bool>("Visibility");

                    b.HasKey("Links");

                    b.ToTable("LinksDbSet");
                });

            modelBuilder.Entity("NotificationPro.Entities.User", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Link");

                    b.Property<string>("Password");

                    b.HasKey("Name");

                    b.ToTable("UserDbSet");
                });
#pragma warning restore 612, 618
        }
    }
}
